/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTransportersRouteImport } from './routes/_authenticated/admin/transporters'
import { Route as AuthenticatedAdminRepsRouteImport } from './routes/_authenticated/admin/reps'
import { Route as AuthenticatedAdminRearersRouteImport } from './routes/_authenticated/admin/rearers'
import { Route as AuthenticatedAdminExtrasRouteImport } from './routes/_authenticated/admin/extras'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminBreedsRouteImport } from './routes/_authenticated/admin/breeds'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTransportersRoute =
  AuthenticatedAdminTransportersRouteImport.update({
    id: '/transporters',
    path: '/transporters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRepsRoute = AuthenticatedAdminRepsRouteImport.update({
  id: '/reps',
  path: '/reps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRearersRoute =
  AuthenticatedAdminRearersRouteImport.update({
    id: '/rearers',
    path: '/rearers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExtrasRoute =
  AuthenticatedAdminExtrasRouteImport.update({
    id: '/extras',
    path: '/extras',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBreedsRoute =
  AuthenticatedAdminBreedsRouteImport.update({
    id: '/breeds',
    path: '/breeds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/extras': typeof AuthenticatedAdminExtrasRoute
  '/admin/rearers': typeof AuthenticatedAdminRearersRoute
  '/admin/reps': typeof AuthenticatedAdminRepsRoute
  '/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/extras': typeof AuthenticatedAdminExtrasRoute
  '/admin/rearers': typeof AuthenticatedAdminRearersRoute
  '/admin/reps': typeof AuthenticatedAdminRepsRoute
  '/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/_authenticated/admin/breeds': typeof AuthenticatedAdminBreedsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/extras': typeof AuthenticatedAdminExtrasRoute
  '/_authenticated/admin/rearers': typeof AuthenticatedAdminRearersRoute
  '/_authenticated/admin/reps': typeof AuthenticatedAdminRepsRoute
  '/_authenticated/admin/transporters': typeof AuthenticatedAdminTransportersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/admin/breeds'
    | '/admin/customers'
    | '/admin/extras'
    | '/admin/rearers'
    | '/admin/reps'
    | '/admin/transporters'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/admin/breeds'
    | '/admin/customers'
    | '/admin/extras'
    | '/admin/rearers'
    | '/admin/reps'
    | '/admin/transporters'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/_authenticated/admin/breeds'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/extras'
    | '/_authenticated/admin/rearers'
    | '/_authenticated/admin/reps'
    | '/_authenticated/admin/transporters'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transporters': {
      id: '/_authenticated/admin/transporters'
      path: '/transporters'
      fullPath: '/admin/transporters'
      preLoaderRoute: typeof AuthenticatedAdminTransportersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reps': {
      id: '/_authenticated/admin/reps'
      path: '/reps'
      fullPath: '/admin/reps'
      preLoaderRoute: typeof AuthenticatedAdminRepsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rearers': {
      id: '/_authenticated/admin/rearers'
      path: '/rearers'
      fullPath: '/admin/rearers'
      preLoaderRoute: typeof AuthenticatedAdminRearersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/extras': {
      id: '/_authenticated/admin/extras'
      path: '/extras'
      fullPath: '/admin/extras'
      preLoaderRoute: typeof AuthenticatedAdminExtrasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/breeds': {
      id: '/_authenticated/admin/breeds'
      path: '/breeds'
      fullPath: '/admin/breeds'
      preLoaderRoute: typeof AuthenticatedAdminBreedsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBreedsRoute: typeof AuthenticatedAdminBreedsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminExtrasRoute: typeof AuthenticatedAdminExtrasRoute
  AuthenticatedAdminRearersRoute: typeof AuthenticatedAdminRearersRoute
  AuthenticatedAdminRepsRoute: typeof AuthenticatedAdminRepsRoute
  AuthenticatedAdminTransportersRoute: typeof AuthenticatedAdminTransportersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBreedsRoute: AuthenticatedAdminBreedsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminExtrasRoute: AuthenticatedAdminExtrasRoute,
  AuthenticatedAdminRearersRoute: AuthenticatedAdminRearersRoute,
  AuthenticatedAdminRepsRoute: AuthenticatedAdminRepsRoute,
  AuthenticatedAdminTransportersRoute: AuthenticatedAdminTransportersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
